# Generated by Django 5.2.4 on 2025-08-26 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate')], default='candidate', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='interviews.user')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('duration_minutes', models.CharField(max_length=20)),
                ('technology', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('overall_score', models.PositiveIntegerField()),
                ('performance_text', models.TextField()),
                ('technical_knowledge', models.PositiveIntegerField()),
                ('problem_solving', models.PositiveIntegerField()),
                ('code_quality', models.PositiveIntegerField()),
                ('confidence', models.PositiveIntegerField()),
                ('mcq_correct', models.PositiveIntegerField()),
                ('mcq_total', models.PositiveIntegerField()),
                ('mcq_time_taken', models.CharField(max_length=20)),
                ('mcq_accuracy', models.PositiveIntegerField()),
                ('strong_areas', models.CharField(max_length=255)),
                ('improvement_areas', models.CharField(max_length=255)),
                ('coding_problems_solved', models.PositiveIntegerField()),
                ('coding_problems_total', models.PositiveIntegerField()),
                ('coding_test_cases_passed', models.PositiveIntegerField()),
                ('coding_test_cases_total', models.PositiveIntegerField()),
                ('coding_avg_time_per_problem', models.CharField(max_length=20)),
                ('coding_code_quality', models.PositiveIntegerField()),
                ('best_solution', models.CharField(max_length=255)),
                ('optimization_needed', models.CharField(max_length=255)),
                ('overall_confidence', models.PositiveIntegerField()),
                ('eye_contact', models.PositiveIntegerField()),
                ('voice_clarity', models.PositiveIntegerField()),
                ('facial_expressions', models.PositiveIntegerField()),
                ('strengths', models.CharField(max_length=255)),
                ('suggestions', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='interviews.user')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('degree', models.CharField(max_length=100)),
                ('job_domain', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, default='candidate_images/default_profile.png', null=True, upload_to='candidate_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='interviews.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='interviews.user')),
            ],
        ),
    ]
