# Generated by Django 5.2.4 on 2025-08-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(blank=True, default='candidate_images/default_profile.png', null=True, upload_to='candidate_images/'),
        ),
    ]
