# Generated by Django 5.2.4 on 2025-08-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_adminprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(default='candidate_images/default_profile.png', upload_to='candidate_images/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='image',
            field=models.ImageField(default='candidate_images/default_profile.png', upload_to='candidate_images/'),
        ),
    ]
