# Generated by Django 5.2.4 on 2025-08-27 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_adminprofile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
