# Generated by Django 5.2.4 on 2025-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('q_no', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('code_part', models.TextField(blank=True, null=True)),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('answer', models.CharField(choices=[('a', 'Option A'), ('b', 'Option B'), ('c', 'Option C'), ('d', 'Option D')], max_length=1)),
            ],
        ),
    ]
