# Generated by Django 5.2.4 on 2025-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_mcq'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mcq',
            name='topics',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
