# Generated by Django 5.2.4 on 2025-09-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_mcq_difficulty_mcq_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
